name: Build LH Launcher
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Compile LH EX
        run: csc /target:winexe /out:LH_EX.exe /r:System.Windows.Forms.dll /r:System.Drawing.dll main.cs
      - name: Release LH EX
        uses: actions/upload-artifact@v3
        with:
          name: LH_EX_PC
          path: LH_EX.exe
