name: Build LH Launcher
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile LH EX
        # Мы указываем прямой путь к компилятору, который есть на каждом Windows-сервере GitHub
        run: |
          & "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /target:winexe /out:LH_EX.exe /r:System.Windows.Forms.dll /r:System.Drawing.dll /r:System.dll /r:Accessibility.dll main.cs

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LH_EX_PC
          path: LH_EX.exe
